name: trippytip
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
  firebase: ^7.3.3
  image_picker: ^0.6.7+15
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+3
  path:
  http: ^0.12.2
  flutter_staggered_grid_view: ^0.3.3
  fluttertoast: ^7.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - images/logo_size_invert.jpg


